- name: Check number
  hosts: localhost
  vars_prompt:
    - name: number
      type: int
      description: "Enter a number to check if it's even or odd"
      prompt: "Please enter a number"
      private: no
  tasks:
    - name: Ensure the number is defined
      ansible.builtin.assert:
        that:
          - number is defined
        success_msg: "The number {{ number }} is defined."
        fail_msg: "No number was provided."

    - name: Ensure the number is an integer
      ansible.builtin.assert:
        that:
          - number is integer
        success_msg: "The number {{ number }} is an integer."
        fail_msg: "The input {{ number }} is not an integer."

    - name: Ensure the number is non-negative
      ansible.builtin.assert:
        that:
          - number >= 0
        success_msg: "The number {{ number }} is non-negative."
        fail_msg: "The number {{ number }} is negative."
    - name: Ensure the number is less than 100
      ansible.builtin.assert:
        that:
          - number < 10
        success_msg: "The number {{ number }} is less than 10."
        fail_msg: "The number {{ number }} is 10 or greater."

    - name: Check if the given number is even or odd
      ansible.buildin.assert:
        that:
          - number % 2 == 0
        success_msg: "The number {{ number }} is even."
        fail_msg: "The number {{ number }} is odd."
      when: number is defined
