- name: Calculate Even or Odd Number
  hosts: localhost
  vars_prompt:
    - name: number
      #type: int #getting error when using type: int
      prompt: Plese enter your number
      private: false

  tasks:
    - name: Ensure the number is defined
      ansible.builtin.assert:
        that:
          - number is defined
        success_msg: "The number {{ number }} is defined."
        fail_msg: "No number was provided."

    - name: Ensure the number is an integer
      ansible.builtin.assert:
        that:
          - number | int  is integer
        success_msg: "The number {{ number | int }} is an integer."
        fail_msg: "The input {{ number | int }} is not an integer."

    - name: Ensure the number is non-negative
      ansible.builtin.assert:
        that:
          - number  | int >= 0
        success_msg: "The number {{ number | int }} is non-negative."
        fail_msg: "The number {{ number | int }} is negative."

    - name: Ensure the number is less than 100
      ansible.builtin.assert:
        that:
          - number | int < 100
        success_msg: "The number {{ number | int }} is less than 100."
        fail_msg: "The number {{ number | int }} is 100 or greater."

    - name: Check if the given number | int is even or odd
      ansible.builtin.assert:
        that:
          - (number | int % 2) == 0
        success_msg: "The number {{ number | int }} is even."
        fail_msg: "The number {{ number | int }} is odd."
      when: number is defined
