- name: default value
  hosts: localhost
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg: "The default value is {{ name | default('Ansible') }}"
- name: Upper Case
  hosts: localhost
  vars:
    name: "Ansible"
  tasks:
    - name: Print Upper Case Name
      ansible.builtin.debug:
        msg: "The upper case name is {{ name | upper }}"
