- name: Install packages
  hosts: all
  become: yes
  tasks:
    - name: Install Packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state}}"
      loop:
        - { name: git, state: present }
        - { name: vim, state: absent }
        - { name: curl, state: present }
        - { name: htop, state: present }
        - { name: tree, state: present }
